"""Change complainer_id

Revision ID: 241e23ad0f1c
Revises: 3eec5ad7cc59
Create Date: 2023-05-14 10:30:48.350059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241e23ad0f1c'
down_revision = '3eec5ad7cc59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complainer_id', sa.Integer(), nullable=False))
    op.drop_constraint('complaints_Complainer_id_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['complainer_id'], ['id'])
    op.drop_column('complaints', 'Complainer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('Complainer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_Complainer_id_fkey', 'complaints', 'users', ['Complainer_id'], ['id'])
    op.drop_column('complaints', 'complainer_id')
    # ### end Alembic commands ###
